import Foundation
import Testing
@testable import LocalmemCore

@Suite("ExtractionBackend")
struct ExtractionBackendTests {
    @Test("storageValue round-trips through init")
    func roundTrip() {
        for backend in [ExtractionBackend.apple, .agent("claude-code"), .agent("codex")] {
            #expect(ExtractionBackend(storageValue: backend.storageValue) == backend)
        }
    }

    @Test("storageValue uses the documented encoding")
    func encoding() {
        #expect(ExtractionBackend.apple.storageValue == "apple")
        #expect(ExtractionBackend.agent("claude-code").storageValue == "agent:claude-code")
    }

    @Test("init rejects an unrecognized storage value")
    func rejectsGarbage() {
        #expect(ExtractionBackend(storageValue: "openai") == nil)
        #expect(ExtractionBackend(storageValue: "") == nil)
    }

    @Test("isOnDevice is true only for the Apple backend")
    func isOnDevice() {
        #expect(ExtractionBackend.apple.isOnDevice)
        #expect(!ExtractionBackend.agent("claude-code").isOnDevice)
    }
}

@Suite("FactParsing")
struct FactParsingTests {
    @Test("A plain JSON array decodes into facts")
    func plainArray() {
        let facts = FactParsing.parse(#"[{"title":"Coffee","content":"Likes oat milk.","type":"preference","tags":["coffee"]}]"#)
        #expect(facts.count == 1)
        #expect(facts.first?.title == "Coffee")
        #expect(facts.first?.type == .preference)
        #expect(facts.first?.tags == ["coffee"])
    }

    @Test("Markdown code fences are stripped before parsing")
    func stripsFences() {
        let raw = "```json\n[{\"title\":\"T\",\"content\":\"C.\",\"type\":\"fact\",\"tags\":[]}]\n```"
        #expect(FactParsing.parse(raw).count == 1)
        // Bare ``` fences (no language tag) too.
        let bare = "```\n[{\"title\":\"T\",\"content\":\"C.\",\"type\":\"fact\",\"tags\":[]}]\n```"
        #expect(FactParsing.parse(bare).count == 1)
    }

    @Test("An array embedded in prose is isolated")
    func isolatesArrayInProse() {
        let raw = #"Sure, here are the facts: [{"title":"T","content":"C.","type":"fact","tags":[]}] Hope that helps!"#
        #expect(FactParsing.parse(raw).count == 1)
    }

    @Test("An unrecognized type falls back to .note")
    func unknownTypeFallsBack() {
        let facts = FactParsing.parse(#"[{"title":"T","content":"C.","type":"whatever","tags":[]}]"#)
        #expect(facts.first?.type == .note)
        // A missing type also becomes .note.
        #expect(FactParsing.parse(#"[{"title":"T","content":"C."}]"#).first?.type == .note)
    }

    @Test("Rows missing a title or content are dropped")
    func dropsIncompleteRows() {
        let raw = #"[{"title":"","content":"C."},{"title":"T","content":""},{"content":"C."},{"title":"Good","content":"Kept."}]"#
        let facts = FactParsing.parse(raw)
        #expect(facts.count == 1)
        #expect(facts.first?.title == "Good")
    }

    @Test("Tags are lowercased and empty tags removed")
    func normalizesTags() {
        let facts = FactParsing.parse(#"[{"title":"T","content":"C.","type":"fact","tags":["Coffee","","DRINK"]}]"#)
        #expect(facts.first?.tags == ["coffee", "drink"])
    }

    @Test("Non-JSON or array-less text yields no facts")
    func noArray() {
        #expect(FactParsing.parse("There is nothing worth remembering.").isEmpty)
        #expect(FactParsing.parse("").isEmpty)
        #expect(FactParsing.parse("[not valid json").isEmpty)
    }
}

@Suite("BoilerplateFilter")
struct BoilerplateFilterTests {
    private func f(_ title: String, _ content: String) -> ExtractedFact {
        ExtractedFact(title: title, content: content, type: .fact, tags: [])
    }

    @Test("Ordinary facts are kept")
    func keepsRealFacts() {
        #expect(BoilerplateFilter.keep(f("Fluid Mechanics course",
            "Is taking Fluid Mechanics (ME21201), a 4-credit course.")))
        #expect(BoilerplateFilter.keep(f("Coffee preference", "Prefers oat-milk flat whites.")))
    }

    @Test("Signature and authorization lines are dropped")
    func dropsSignatures() {
        #expect(BoilerplateFilter.isBoilerplate(f("Signature of HOD/HOS/HOC", "Signature of the Head of Department.")))
        #expect(BoilerplateFilter.isBoilerplate(f("Approval", "Signed by the registrar.")))
        #expect(BoilerplateFilter.isBoilerplate(f("Note", "For office use only.")))
    }

    @Test("Generation and print metadata are dropped")
    func dropsGenerationMetadata() {
        #expect(BoilerplateFilter.isBoilerplate(f("Generation Date", "Jul 8, 2026 10:21 AM.")))
        #expect(BoilerplateFilter.isBoilerplate(f("Footer", "Generated by ERP, IIT KGP.")))
    }

    @Test("Page-number footers are dropped")
    func dropsPageNumbers() {
        #expect(BoilerplateFilter.isBoilerplate(f("Footer", "Page 2 of 5")))
        // But a page count mentioned in a real sentence is not boilerplate.
        #expect(BoilerplateFilter.keep(f("Thesis length", "The dissertation runs to 240 pages.")))
    }

    @Test("Empty and label-only facts are dropped")
    func dropsEmptyAndLabelOnly() {
        #expect(BoilerplateFilter.isBoilerplate(f("Roll No.", "")))
        #expect(BoilerplateFilter.isBoilerplate(f("Roll No.", "roll no.")))   // case-insensitive echo
    }
}
